#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

export BENCH_ENABLE_CANONICALIZATION=true
export BENCH_SCENARIOS="${BENCH_SCENARIOS:-canonicalization}"
export PSM_CANONICALIZATION_ENABLED=true
export PSM_CANONICALIZATION_CHECK_INTERVAL_SECS="${PSM_CANONICALIZATION_CHECK_INTERVAL_SECS:-1}"
export PSM_CANONICALIZATION_MAX_RETRIES="${PSM_CANONICALIZATION_MAX_RETRIES:-2}"
export BENCH_CANONICALIZATION_POLL_INTERVAL_MS="${BENCH_CANONICALIZATION_POLL_INTERVAL_MS:-250}"
export BENCH_CANONICALIZATION_TIMEOUT_SECS="${BENCH_CANONICALIZATION_TIMEOUT_SECS:-90}"

"$SCRIPT_DIR/run_postgres.sh"
