// This file is generated by scripts/generate-masm.mjs from the MASM contract sources.
// Do not edit it by hand.

export const MULTISIG_ACCOUNT_COMPONENT_MASM = `# Multi-Signature RPO Falcon 512 Authentication Component

use openzeppelin::auth::multisig

pub use multisig::update_signers_and_threshold
pub use multisig::update_procedure_threshold

@auth_script
pub proc auth_tx_multisig(salt: word)
    exec.multisig::auth_tx
    exec.multisig::assert_new_tx
end
`;

export const MULTISIG_GUARDIAN_ACCOUNT_COMPONENT_MASM = `# Multi-Signature RPO Falcon 512 Authentication Component With GUARDIAN

use openzeppelin::auth::multisig
use openzeppelin::auth::guardian

pub use multisig::update_signers_and_threshold
pub use multisig::update_procedure_threshold
pub use guardian::update_guardian_public_key
pub use guardian::verify_guardian_signature

@auth_script
pub proc auth_tx_multisig_guardian(salt: word)
    exec.multisig::auth_tx
    exec.guardian::verify_guardian_signature
    exec.multisig::assert_new_tx
end
`;

export const MULTISIG_ECDSA_ACCOUNT_COMPONENT_MASM = `# Multi-Signature ECDSA secp256k1 Authentication Component

use openzeppelin::auth::multisig_ecdsa

pub use multisig_ecdsa::update_signers_and_threshold
pub use multisig_ecdsa::update_procedure_threshold

@auth_script
pub proc auth_tx_multisig_ecdsa(salt: word)
    exec.multisig_ecdsa::auth_tx
    exec.multisig_ecdsa::assert_new_tx
end
`;

export const MULTISIG_GUARDIAN_ECDSA_ACCOUNT_COMPONENT_MASM = `# Multi-Signature ECDSA secp256k1 Authentication Component With GUARDIAN

use openzeppelin::auth::multisig_ecdsa
use openzeppelin::auth::guardian_ecdsa

pub use multisig_ecdsa::update_signers_and_threshold
pub use multisig_ecdsa::update_procedure_threshold
pub use guardian_ecdsa::update_guardian_public_key
pub use guardian_ecdsa::verify_guardian_signature

@auth_script
pub proc auth_tx_multisig_guardian_ecdsa(salt: word)
    exec.multisig_ecdsa::auth_tx
    exec.guardian_ecdsa::verify_guardian_signature
    exec.multisig_ecdsa::assert_new_tx
end
`;
