version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - guardian-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=guardian
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=guardian
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guardian -d guardian"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  guardian-postgres:
