version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - psm-app:/var/psm/app
    environment:
      - RUST_LOG=info
      - PSM_APP_PATH=/var/psm/app

volumes:
  psm-app:
