import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, '..');
const repoRoot = path.resolve(packageRoot, '../..');
const packageMasmDir = path.join(packageRoot, 'masm');
const canonicalMasmDir = path.join(repoRoot, 'crates', 'contracts', 'masm');
const generatedAccountDir = path.join(packageRoot, 'src', 'account');
const masmFiles = [
  {
    canonicalPath: ['auth', 'multisig.masm'],
    packagedPath: ['auth', 'multisig.masm'],
    exportName: 'MULTISIG_MASM',
    generatedPath: ['masm', 'auth.ts'],
  },
  {
    canonicalPath: ['auth', 'multisig_ecdsa.masm'],
    packagedPath: ['auth', 'multisig_ecdsa.masm'],
    exportName: 'MULTISIG_ECDSA_MASM',
    generatedPath: ['masm', 'auth.ts'],
  },
  {
    canonicalPath: ['auth', 'guardian.masm'],
    packagedPath: ['auth', 'guardian.masm'],
    exportName: 'GUARDIAN_MASM',
    generatedPath: ['masm', 'auth.ts'],
  },
  {
    canonicalPath: ['auth', 'guardian_ecdsa.masm'],
    packagedPath: ['auth', 'guardian_ecdsa.masm'],
    exportName: 'GUARDIAN_ECDSA_MASM',
    generatedPath: ['masm', 'auth.ts'],
  },
  {
    canonicalPath: ['account_components', 'auth', 'multisig.masm'],
    packagedPath: ['account_components', 'auth', 'multisig.masm'],
    exportName: 'MULTISIG_ACCOUNT_COMPONENT_MASM',
    generatedPath: ['masm', 'account-components', 'auth.ts'],
  },
  {
    canonicalPath: ['account_components', 'auth', 'multisig_guardian.masm'],
    packagedPath: ['account_components', 'auth', 'multisig_guardian.masm'],
    exportName: 'MULTISIG_GUARDIAN_ACCOUNT_COMPONENT_MASM',
    generatedPath: ['masm', 'account-components', 'auth.ts'],
  },
  {
    canonicalPath: ['account_components', 'auth', 'multisig_ecdsa.masm'],
    packagedPath: ['account_components', 'auth', 'multisig_ecdsa.masm'],
    exportName: 'MULTISIG_ECDSA_ACCOUNT_COMPONENT_MASM',
    generatedPath: ['masm', 'account-components', 'auth.ts'],
  },
  {
    canonicalPath: ['account_components', 'auth', 'multisig_guardian_ecdsa.masm'],
    packagedPath: ['account_components', 'auth', 'multisig_guardian_ecdsa.masm'],
    exportName: 'MULTISIG_GUARDIAN_ECDSA_ACCOUNT_COMPONENT_MASM',
    generatedPath: ['masm', 'account-components', 'auth.ts'],
  },
];

function fileExists(rootDir, pathSegments) {
  return existsSync(path.join(rootDir, ...pathSegments));
}

function resolveSourceDir() {
  const canonicalAvailable = masmFiles.every(({ canonicalPath }) =>
    fileExists(canonicalMasmDir, canonicalPath),
  );
  if (canonicalAvailable) {
    return canonicalMasmDir;
  }

  const packagedAvailable = masmFiles.every(({ packagedPath }) =>
    fileExists(packageMasmDir, packagedPath),
  );
  if (packagedAvailable) {
    return packageMasmDir;
  }

  throw new Error(
    `unable to locate MASM sources in either '${canonicalMasmDir}' or '${packageMasmDir}'`,
  );
}

function writeIfChanged(filePath, contents) {
  if (existsSync(filePath) && readFileSync(filePath, 'utf8') === contents) {
    return;
  }

  writeFileSync(filePath, contents, 'utf8');
}

function toTemplateLiteral(contents) {
  return `\`${contents
    .replaceAll('\\', '\\\\')
    .replaceAll('`', '\\`')
    .replaceAll('${', '\\${')}\``;
}

const sourceDir = resolveSourceDir();
const usingCanonicalSources = sourceDir === canonicalMasmDir;
const masmSources = masmFiles.map(({ canonicalPath, packagedPath, generatedPath, exportName }) => ({
  packagedPath,
  exportName,
  generatedPath,
  source: readFileSync(
    path.join(sourceDir, ...(usingCanonicalSources ? canonicalPath : packagedPath)),
    'utf8',
  ),
}));

for (const { packagedPath, source } of masmSources) {
  const destination = path.join(packageMasmDir, ...packagedPath);
  mkdirSync(path.dirname(destination), { recursive: true });
  writeIfChanged(destination, source);
}

const generatedModules = new Map();

for (const { generatedPath, exportName, source } of masmSources) {
  const key = generatedPath.join('/');
  const exportsSource = generatedModules.get(key) ?? [];
  exportsSource.push(`export const ${exportName} = ${toTemplateLiteral(source)};`);
  generatedModules.set(key, exportsSource);
}

for (const [generatedPath, exportsSource] of generatedModules.entries()) {
  const destination = path.join(generatedAccountDir, ...generatedPath.split('/'));
  const generatedSource = `// This file is generated by scripts/generate-masm.mjs from the MASM contract sources.
// Do not edit it by hand.

${exportsSource.join('\n\n')}
`;
  mkdirSync(path.dirname(destination), { recursive: true });
  writeIfChanged(destination, generatedSource);
}

writeIfChanged(
  path.join(generatedAccountDir, 'masm', 'index.ts'),
  `// This file is generated by scripts/generate-masm.mjs from the MASM contract sources.
// Do not edit it by hand.

export * from './auth.js';
export * from './account-components/auth.js';
`,
);

writeIfChanged(
  path.join(generatedAccountDir, 'masm.ts'),
  `// This file is generated by scripts/generate-masm.mjs from the MASM contract sources.
// Do not edit it by hand.

export * from './masm/index.js';
`,
);
