// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `states` table.
    ///
    /// (Automatically generated by Diesel.)
    states (account_id) {
        #[max_length = 128]
        account_id -> Varchar,
        state_json -> Jsonb,
        #[max_length = 128]
        commitment -> Varchar,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `deltas` table.
    ///
    /// (Automatically generated by Diesel.)
    deltas (id) {
        id -> Int8,
        #[max_length = 128]
        account_id -> Varchar,
        nonce -> Int8,
        #[max_length = 128]
        prev_commitment -> Varchar,
        #[max_length = 128]
        new_commitment -> Nullable<Varchar>,
        delta_payload -> Jsonb,
        ack_sig -> Nullable<Text>,
        status -> Jsonb,
        // Typed mirrors of the lifecycle status. Promoted in
        // migration 2026-05-10-000001 for fast dashboard reads
        // (feature `005-operator-dashboard-metrics`). Writes
        // dual-populate these alongside the Jsonb `status`; reads
        // (especially cross-account aggregates) prefer the typed
        // columns.
        status_kind -> Text,
        status_timestamp -> Timestamptz,
        // Push-time-derived enrichment metadata. Written by
        // `push_delta` before `submit_delta`; canonicalization only
        // flips status and never touches this column. The upsert
        // path uses `COALESCE(EXCLUDED.metadata, deltas.metadata)` so
        // a later status flip never overwrites an existing typed blob.
        metadata -> Nullable<Jsonb>,
    }
}

diesel::table! {
    /// Representation of the `delta_proposals` table.
    ///
    /// (Automatically generated by Diesel.)
    delta_proposals (id) {
        id -> Int8,
        #[max_length = 128]
        account_id -> Varchar,
        #[max_length = 128]
        commitment -> Varchar,
        nonce -> Int8,
        #[max_length = 128]
        prev_commitment -> Varchar,
        #[max_length = 128]
        new_commitment -> Nullable<Varchar>,
        delta_payload -> Jsonb,
        ack_sig -> Nullable<Text>,
        status -> Jsonb,
        status_kind -> Text,
        status_timestamp -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `account_metadata` table.
    ///
    /// (Automatically generated by Diesel.)
    account_metadata (account_id) {
        #[max_length = 128]
        account_id -> Varchar,
        auth -> Jsonb,
        network_config -> Jsonb,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        has_pending_candidate -> Bool,
        last_auth_timestamp -> Nullable<Int8>,
        paused_at -> Nullable<Timestamptz>,
        paused_reason -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `admin_actions` table.
    ///
    /// Feature 006-operator-authz append-only audit trail. Inserts only;
    /// UPDATE/DELETE blocked by the `admin_actions_no_update` trigger
    /// defined in the matching migration.
    admin_actions (id) {
        id -> Int8,
        occurred_at -> Timestamptz,
        operator_identity -> Text,
        action_kind -> Text,
        target_account_id -> Nullable<Text>,
        payload -> Jsonb,
        outcome -> Text,
        error_code -> Nullable<Text>,
        client_ip -> Nullable<Text>,
    }
}

diesel::table! {
    /// Single-row store-level encryption marker. Its presence indicates the
    /// store is encrypted.
    storage_encryption_marker (id) {
        id -> Bool,
        scheme_version -> Int2,
        init_kid -> Text,
    }
}

diesel::allow_tables_to_appear_in_same_query!(states, deltas, delta_proposals, account_metadata,);
