// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `states` table.
    ///
    /// (Automatically generated by Diesel.)
    states (account_id) {
        #[max_length = 64]
        account_id -> Varchar,
        state_json -> Jsonb,
        #[max_length = 128]
        commitment -> Varchar,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `deltas` table.
    ///
    /// (Automatically generated by Diesel.)
    deltas (id) {
        id -> Int8,
        #[max_length = 64]
        account_id -> Varchar,
        nonce -> Int8,
        #[max_length = 128]
        prev_commitment -> Varchar,
        #[max_length = 128]
        new_commitment -> Nullable<Varchar>,
        delta_payload -> Jsonb,
        ack_sig -> Nullable<Text>,
        status -> Jsonb,
    }
}

diesel::table! {
    /// Representation of the `delta_proposals` table.
    ///
    /// (Automatically generated by Diesel.)
    delta_proposals (id) {
        id -> Int8,
        #[max_length = 64]
        account_id -> Varchar,
        #[max_length = 128]
        commitment -> Varchar,
        nonce -> Int8,
        #[max_length = 128]
        prev_commitment -> Varchar,
        #[max_length = 128]
        new_commitment -> Nullable<Varchar>,
        delta_payload -> Jsonb,
        ack_sig -> Nullable<Text>,
        status -> Jsonb,
    }
}

diesel::table! {
    /// Representation of the `account_metadata` table.
    ///
    /// (Automatically generated by Diesel.)
    account_metadata (account_id) {
        #[max_length = 64]
        account_id -> Varchar,
        auth -> Jsonb,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        has_pending_candidate -> Bool,
    }
}

diesel::allow_tables_to_appear_in_same_query!(states, deltas, delta_proposals, account_metadata,);
